modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mysticalrealms"
version="1.0.0"
displayName="MysticalRealms"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jpdal, MCreator"

[[dependencies.mysticalrealms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




